version: '3'
services:
  app:
    build: app/
    command: flask run --host=0.0.0.0 --port=3000
    environment:
      DB_PATH: /data/petition.sqlite3
      RENDER_PATH: /html
      FLASK_ENV: development
    volumes:
      - './app/petition_counts:/app'
      - './data:/data'
      - './html:/html'
    ports:
      - '3000:3000'
