apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: petitions
spec:
  acme:
    config:
      - http01:
          ingress: petition-count
        domains:
          - petition.rossmasters.com
  commonName: petition.rossmasters.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: petition-tls
