apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petition-counts-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

